SET(PROJECT_NAME_TESTS ${PROJECT_NAME}-unit-tests)    
IF(WITH_TESTS AND PROJECT_NAME_TESTS MATCHES "${WITH_TESTS}")
    MESSAGE("~~ Building ${PROJECT_NAME_TESTS}")

    SET_PROPERTY(DIRECTORY PROPERTY TEST_MODULES "${PROJECT_NAME_TESTS}")

    FIND_PACKAGE(Boost ${Boost_MIN_VERSION} COMPONENTS program_options REQUIRED)

    SET(TESTS_ROOT test)

    LINK_DIRECTORIES(${GTEST_ROOT}/lib)

    FILE(GLOB_RECURSE TEST_SOURCE_FILES "${TESTS_ROOT}/*.cpp")
    FOREACH(DEP ${TEST_DEPENDENCIES})
        INCLUDE_DIRECTORIES(../${DEP}/include)
    ENDFOREACH(DEP)

    ADD_EXECUTABLE(${PROJECT_NAME_TESTS} ${TEST_SOURCE_FILES} ${ADDITIONAL_TEST_SOURCE_FILES})

    TARGET_LINK_LIBRARIES(${PROJECT_NAME_TESTS} gtest gtest_main ${Boost_LIBRARIES} pthread m boost_system boost_thread ${DEPENDENCIES} ${TEST_DEPENDENCIES})
ENDIF()

