SET(PROJECT_NAME_TESTS ${PROJECT_NAME}-unit-tests)    
IF(WITH_TESTS AND PROJECT_NAME_TESTS MATCHES "${WITH_TESTS}")
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_PEDANTIC_FLAGS}")

    message("~~ Building ${PROJECT_NAME_TESTS}")

    set_property(DIRECTORY PROPERTY TEST_MODULES "${PROJECT_NAME_TESTS}")

    SET(GTEST_ROOT ../../libs/gtest-1.7.0)
    LINK_DIRECTORIES(${GTEST_ROOT}/build)
    INCLUDE_DIRECTORIES(${GTEST_ROOT}/include)

    FIND_PACKAGE(Boost ${Boost_MIN_VERSION} COMPONENTS program_options REQUIRED)

    SET(TESTS_ROOT test)

    link_directories(${GTEST_ROOT}/lib)

    FILE(GLOB_RECURSE TEST_SOURCE_FILES "${TESTS_ROOT}/*.cpp")
    
    ADD_EXECUTABLE(${PROJECT_NAME_TESTS} ${TEST_SOURCE_FILES} ${ADDITIONAL_TEST_SOURCE_FILES})
    TARGET_LINK_LIBRARIES(${PROJECT_NAME_TESTS} ${DEPENDENCIES} ${TEST_DEPENDENCIES} gtest gtest_main ${Boost_LIBRARIES} -lpthread -lm -lboost_system -lboost_thread -liomp5)
ENDIF()

