#
# Removes the specified compile flag from the specified target.
#   _target     - The target to remove the compile flag from
#   _flag       - The compile flag to remove
#
# Pre: apply_global_cxx_flags_to_all_targets() must be invoked.
#
macro(remove_compile_flag_from_target _target _flag)
    get_target_property(_target_cxx_flags ${_target} COMPILE_OPTIONS)
    # message("found compile options ${_target_cxx_flags}")
    if(_target_cxx_flags)
        list(REMOVE_ITEM _target_cxx_flags ${_flag})
        set_target_properties(${_target} PROPERTIES COMPILE_OPTIONS "${_target_cxx_flags}")
    endif()
    get_target_property(_target_cxx_flags ${_target} INTERFACE_COMPILE_OPTIONS)
    # message("found compile options ${_target_cxx_flags}")
    if(_target_cxx_flags)
        list(REMOVE_ITEM _target_cxx_flags ${_flag})
        set_target_properties(${_target} PROPERTIES INTERFACE_COMPILE_OPTIONS "${_target_cxx_flags}")
    endif()
endmacro()

macro(remove_link_flag_from_target _target _flag)
    get_target_property(_target_cxx_flags ${_target} LINK_OPTIONS)
    # message("found target link options ${_target_cxx_flags}")
    if(_target_cxx_flags)
        list(REMOVE_ITEM _target_cxx_flags ${_flag})
        set_target_properties(${_target} PROPERTIES LINK_OPTIONS "${_target_cxx_flags}")
    endif()
    get_target_property(_target_cxx_flags ${_target} INTERFACE_LINK_OPTIONS)
    # message("found target link options ${_target_cxx_flags}")
    if(_target_cxx_flags)
        list(REMOVE_ITEM _target_cxx_flags ${_flag})
        set_target_properties(${_target} PROPERTIES INTERFACE_LINK_OPTIONS "${_target_cxx_flags}")
    endif()
endmacro()

macro(remove_compile_flag_from_dir _flag)
    get_directory_property(_dir_compile_flags COMPILE_OPTIONS)
    if(_dir_compile_flags)
        list(REMOVE_ITEM _dir_compile_flags ${_flag})
        set_directory_properties(PROPERTIES COMPILE_OPTIONS "${_dir_compile_flags}")
    endif()
    get_directory_property(_dir_compile_flags INTERFACE_COMPILE_OPTIONS)
    if(_dir_compile_flags)
        list(REMOVE_ITEM _dir_compile_flags ${_flag})
        set_directory_properties(PROPERTIES INTERFACE_COMPILE_OPTIONS "${_dir_compile_flags}")
    endif()
endmacro()

macro(remove_link_flag_from_dir _flag)
    get_directory_property(_dir_link_flags LINK_OPTIONS)
    # message("found directory link options ${_target_cxx_flags}")
    if(_dir_link_flags)
        list(REMOVE_ITEM _dir_link_flags ${_flag})
        set_directory_properties(PROPERTIES LINK_OPTIONS "${_dir_link_flags}")
    endif()
    get_directory_property(_dir_link_flags INTERFACE_LINK_OPTIONS)
    if(_dir_link_flags)
        list(REMOVE_ITEM _dir_link_flags ${_flag})
        set_directory_properties(PROPERTIES INTERFACE_LINK_OPTIONS "${_dir_link_flags}")
    endif()
endmacro()

macro(remove_build_flag _target _flag)
    REMOVE_COMPILE_FLAG_FROM_TARGET(${_target} ${_flag})
    REMOVE_LINK_FLAG_FROM_TARGET(${_target} ${_flag})
    REMOVE_COMPILE_FLAG_FROM_DIR(${_flag})
    REMOVE_LINK_FLAG_FROM_DIR(${_flag})
endmacro()

macro(remove_dir_flag _flag)
    REMOVE_COMPILE_FLAG_FROM_DIR(${_flag})
    REMOVE_LINK_FLAG_FROM_DIR(${_flag})
endmacro()
